[pytest]
minversion = 6.0
addopts =
    -ra
    -q
    --strict-markers
    --strict-config
    --ds=backend.settings
testpaths = .
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
DJANGO_SETTINGS_MODULE = backend.settings
